### ISSUE TITLE
cannot find the function of clonalNetwork()

### ISSUE THREAD

**Issue by mieko-cc** [ncborcherding/scRepertoire#127] opened 2021-12-06 16:57 UTC
Thanks for the nice function of clonalNetwork(), but in the version of scRepertoire1.4.0, this function can not work, and I can not install the more development version.
Could you please show me how to use clonalNetwork() ?
Thank you！

**Comment by ncborcherding** [comment] 2021-12-06 17:21
Duplicate of #126 

Need to install the github dev version, see https://github.com/ncborcherding/scRepertoire/issues/126#issuecomment-986983172

**Closed by ncborcherding** 2021-12-06 17:21 UTC
