### ISSUE TITLE
screpertoire individual vs multiple samples - loss of data?

### ISSUE THREAD

**Issue by CAC13** [ncborcherding/scRepertoire#283] opened 2023-12-03 20:21 UTC
Hi Nick,

Highly appreciate all the work you do in the single-cell community - your packages have been very useful on multiple occasions!

I'm having issues with adding 10x VDJ data via scRepertoire in that when using a list of multiple contig files (subsetted from vdjaggr output as don't have access to individual runs at the moment) and applying them to a seurat object containing the matching samples I get much fewer 'hits' with combineExpression than I do if I subset the seurat object for a singular sample and apply only the relevant contig file with combineExpression. 

> length(unique(singular$CTaa))
[1] 657
> length(unique(multiplex$CTaa))
[1] 489

Perhaps I am missing something basic here (and its been a while since I used screpertoire), but I feel like I didn't have this issue previously. I've recently moved workplaces and therefore new PC etc... so all packages should be fairly up to date (scRepertoire 2.0.0).

Best,

Chris

**Comment by CAC13** [comment] 2023-12-04 22:51
Hi @Qile0317,

1. Can confirm I have the latest commit (I had a similar issue as #279 and #281 when adding TRUST4 data but that was solved with the latest commit) but the issue still persists. In fact, I have the same issue as I originally described when trying to add TRUST4 data.

I completely understand the issue of not having example data/minimal reproducible example, but I am very limited by data sharing regulations. A quick test on the inbuilt scRepertoire dataset did not have the same issue.

2. Did not have time to do this but will do so tomorrow and update.

**Comment by ncborcherding** [comment] 2023-12-05 09:59
@CAC13 Also understandable about data confidentiality, but it will limit the troubleshooting. 

Thanks for sharing the code - have you thoroughly check the barcodes of the ```combineTCR()``` output vs single-cell object? 

- Multiplex experiments can have duplicated barcodes - this is generally 1maybe 10-15 cells that have an issue
- Cell Ranger aggr will append a suffix to the barcodes, which will then have a mismatch during ```combineExpression()```

Nick

**Comment by CAC13** [comment] 2023-12-05 12:21
Have checked the following so I don't think its a barcode mismatch issue:
1. Original seurat object barcodes are all unique (modified using code described in scRepertoire vignette) - no duplicates
2. `combineTCR()` output barcodes match the object barcodes perfectly
3. I've now run the same code/objects with scRepertoire v1.11 and end up with what I would be expecting.
```
> length(which(!is.na(subset(test_object_multiplex, sample == "CRC01_WT")$CTaa)))
[1] 1598
> length(which(!is.na(test_object_crc01wt$CTaa)))
[1] 1598
```
So I guess it must be a version specific issue? However, as I mentioned above the scRep inbuilt object had no issues with v2.0.0...

Just in case I also tested with previous versions of Seurat (didn't go past v4.0.1) in case it was an issue with v5 but the issue persisted.

**Comment by Qile0317** [comment] 2023-12-05 20:08
Ah, I think I may know what the problem is, will be working on a fix. Thanks a lot for finding the root cause! I suspect it might be related to the fact that I had changed an internal function to initialize a matrix of "NA" strings. But yea, as you mentioned, most of the changed functions are currently only tested on the built in data which is subject to change

**Comment by noranekonobokkusu** [comment] 2023-12-05 20:26
I also started looking at the integration with my scRNAseq data. What I noticed is that when I use `group.by = "sample",` in combineExpression, I get 10k fewer cells  in `sce@meta.data` annotated with scRep results. If I don't use it, I get the correct number of annotated cells. 

That being said, I was naively expecting that clonalProportion will add up to something round in each of these scenarios, but it doesn't, I get values both above and below 1 per sample when I run this:

<pre>
sce@meta.data %>%
+   group_by(sample) %>%
+   summarize(n=sum(clonalProportion, na.rm = T)) 
</pre>

I renamed barcodes in the combined.TCR from SBM1073_AAACCCAAGTAGGATT to AAACCCAAGTAGGATT-SBM1073.2 to match my sce object, but I haven't looked into the code yet so don't know if that contributes.

**Comment by CAC13** [comment] 2023-12-06 15:03
Hi all,

Appreciate the rapid assistance and help with this - hopefully we have identified the correct issue!

Would you like me to close this or rather wait until the update is pushed and we can confirm?

**Comment by noranekonobokkusu** [comment] 2023-12-15 21:36
@ncborcherding @Qile0317 
Hi,
Is there an update on this issue? I think that line 99 in [combineExpression.R](https://github.com/ncborcherding/scRepertoire/blob/master/R/combineExpression.R) should be 

<pre>
data <- merge(data, data2, by = c(cloneCall, group.by), all = TRUE)
</pre>

instead of 

<pre>
data <- merge(data, data2, by = cloneCall, all = TRUE)
</pre>

as there is no reason to ignore the sample column and to get fewer annotated cells when using a grouping by sample, or do I understand this argument wrong?

**Comment by Qile0317** [comment] 2024-07-25 03:30
@ncborcherding So sorry for being gone for so long, I've been working recently to try and reproduce the issue with little luck - and I just wanted to check up - it appears to me that currently `combineExpression()` still uses the old C++ code I wrote that caused this issue right? And according to @CAC13 this issue isn't present in the old v1.11? Could we actually do a full revert and then try change up the function components one-by-one? I hope this issue hasn't caused any actual researchers to get incorrect results :P

**Comment by ncborcherding** [comment] 2024-07-25 14:48
@Qile0317 

I am not convinced this is an issue from scRepertoire side of things. I have tried multiple data sets to reproduce the error and do not find the discrepancy. I believe this is an issue with mismatched barcodes somewhere or possible duplicate barcodes? ```combineExpression()``` will automatically remove duplicate barcodes.

Here is a reproducible example using the full scRep example using a modified version of the above script:

```
whole_object <- readRDS("/Users/nick/Documents/GitHub/scRepertoire/vignettes/articles/scRep_example_full.rds")
#No barcode duplicates in the large seurat object
length(rownames(whole_object@meta.data))
#> [1] 30105
length(unique(rownames(whole_object@meta.data)))
#> [1] 30105

#creating test objects
multiplex_samples <- c("P17B", "P17L")
test_object_multiplex <- subset(whole_object, orig.ident %in% multiplex_samples)
test_object_P17B <- subset(whole_object, orig.ident == "P17B")

#VDJ filtering
#whole_vdj has already been filtered for barcodes matching with the seurat object
P17B_contig <- contig_list[1]

####multiplex processing
#LoadContigs
multiplex_contig_list <- contig_list[1:2]

#combine TCR contigs
multiple_combined_tcr <- combineTCR(multiplex_contig_list,
                                    samples = c("P17B", "P17L"),
                                    removeNA = F,
                                    removeMulti = F,
                                    filterMulti = T)

#dims of combined TCR lists and intersect with seurat object barcodes
dim(multiple_combined_tcr$P17B)
#> [1] 2805   12
length(intersect(multiple_combined_tcr$P17B$barcode, rownames(test_object_multiplex@meta.data)))
#> [1] 2640

#add combined tcr data to object
test_object_multiplex <- combineExpression(multiple_combined_tcr,
                                           test_object_multiplex,
                                           cloneCall = "aa",
                                           group.by = "sample",
                                           proportion = F,
                                           cloneSize = c(Single=1, Small=5, Medium=15, Large=50, Hyperexpanded=5000))

#combine TCR contigs
P17B_combined_tcr <- combineTCR(P17B_contig,
                                   samples = "P17B",
                                   removeNA = F,
                                   removeMulti = F,
                                   filterMulti = T)

#dims of combined TCR lists and intersect with seurat object barcodes
dim(P17B_combined_tcr$P17B)
#> [1] 2805   12
length(intersect(P17B_combined_tcr$P17B$barcode, rownames(test_object_crc01wt@meta.data)))
#> [1] 2640

#add combined tcr data to object
test_object_P17B <- combineExpression(P17B_combined_tcr,
                                         test_object_P17B,
                                         cloneCall = "aa",
                                         group.by = "sample",
                                         proportion = F,
                                         cloneSize = c(Single=1, Small=5, Medium=15, Large=50, Hyperexpanded=5000))

#####comparing P17B in the multiplex vs singular
dim(subset(test_object_multiplex, orig.ident == "P17B"))
#> [1] 33538  3020
dim(test_object_P17B)
#> [1] 3538  3020


length(intersect(rownames(subset(test_object_multiplex, orig.ident == "P17B")@meta.data),rownames(test_object_P17B@meta.data)))
#> [1] 3020


length(which(!is.na(subset(test_object_multiplex, orig.ident == "P17B")$CTaa)))
#> [1] 2640
length(which(!is.na(test_object_P17B$CTaa)))
#> [1] 2640
```

For now I am going to close this until someone can provide a reproducible example of the problem. 

Nick

**Closed by ncborcherding** 2024-07-25 14:48 UTC
Labels: bug
