### ISSUE TITLE
percentVJ all 0

### ISSUE THREAD

**Issue by jiw181** [ncborcherding/scRepertoire#415] opened 2024-10-08 18:43 UTC
Hello,

For the percentVJ function, I got all 0 in the output for 2 of the samples. However, I am sure the V and J are present for the 2 samples in the Seurat object as shown in the attached file. 
[unknown_error.xlsx](https://github.com/user-attachments/files/17297801/unknown_error.xlsx)

If I only run the 2 samples, I got error: Error in `combine_vars()`:
! Faceting variables must have at least one value

If I only run 1 sample, I got error: 
Error in View : 'names' attribute [1] must be the same length as the vector [0]

Any suggestions?

Many thanks

**Comment by ncborcherding** [comment] 2024-10-08 18:48
Hey @jiw181,

Thanks for reaching out. 

Please make a [reproducible example](http://adv-r.had.co.nz/Reproducibility.html) for this issue so I know what you are experiencing. 

Also with the example, please make sure to include the output of ```sessionInfo()```

Thanks,
Nick

**Comment by jiw181** [comment] 2024-10-08 19:39
Hello Nick @ncborcherding,

Thank you for the prompt response! Please find the .html with sessionInfo and intermediate files attached.
[rstudio-export (47).zip](https://github.com/user-attachments/files/17298382/rstudio-export.47.zip)

Thank you!

**Comment by ncborcherding** [comment] 2024-10-08 20:07
Found the issue - there was an assumption that there would be more than 1 sample during the plotting phase. It looks like subseting it to one specific orig.ident was what was causing it to break. 

Got it fixed and in the dev branch. I will need to do some more testing this week and get it merged to the main branch. 

For now, you can install the dev branch with: 

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

Thanks,
Nick

**Closed by ncborcherding** 2024-10-08 20:07 UTC
Labels: more info needed

**Comment by jiw181** [comment] 2024-10-08 20:12
I will test the dev version and see if it reports correct pct for the 2 samples.
Thank you very much. Have a great day! 😊

From: theHumanBorch ***@***.***>
Date: Tuesday, October 8, 2024 at 4:07 PM
To: ncborcherding/scRepertoire ***@***.***>
Cc: Wang, Jiefei ***@***.***>, Mention ***@***.***>
Subject: Re: [ncborcherding/scRepertoire] percentVJ all 0 (Issue #415)

Found the issue - there was an assumption that there would be more than 1 sample during the plotting phase. It looks like subseting it to one specific orig.ident was what was causing it to break.

Got it fixed and in the dev branch. I will need to do some more testing this week and get it merged to the main branch.

For now, you can install the dev branch with:

***@***.***")

Thanks,
Nick
