### ISSUE TITLE
Error in loading BD rhapsody VDJ results

### ISSUE THREAD

**Issue by RainboWu** [ncborcherding/scRepertoire#229] opened 2023-04-13 04:20 UTC
`contig_list = loadContigs("/data/results/JZscxxxx_VDJ_Dominant_Contigs_AIRR.tsv",format = "BD")`
`combined <- combineBCR(contig_list, sample=NULL)
`
Error in `dictionary[, chain]`:
! Can't subset columns that don't exist.
✖ Column `cdr3_nt1` doesn't exist.

I tried version 1.7.4 from dev branch and 1.8.0 from bioconductor

**Comment by RainboWu** [comment] 2023-04-13 04:54
Oh, I need to input result path ,not the tsv file path.

**Comment by RainboWu** [comment] 2023-04-13 05:17
now ` combined <- combineBCR(contig_list, sample=NULL) ` encounter error 

seem like this code have issue:
 
debug: Con.df <- data.frame(matrix(NA, length(unique_df), 9))
debug: colnames(Con.df) <- c("barcode", heavy_lines, light_lines)
Browse[2]> colnames(Con.df)
[1] "X1" "X2" "X3" "X4" "X5" "X6" "X7" "X8" "X9"

**Comment by ncborcherding** [comment] 2023-04-13 20:06
Hey, 

Thanks for reaching out - would you mind giving me the output of ```sessionInfo()``` and the code you used to create **contig_list**. 

Thanks,
Nick

**Comment by eandresleon** [comment] 2023-04-14 13:22
Hi!

I'm having a similar error where reading AIRR data from a rhapsody.

First if I use the loadContings using a folder:
```

> suppressMessages(library(Seurat))
> suppressMessages(library(scRepertoire))
> contig_list = loadContigs("~/Proyectos/EduardoAndres/Rhapsody/dataset_test/Munain_Run3_NextS/",format = "AIRR")
Error in file(file, "rt") : cannot open the connection
In addition: Warning messages:
1: In file(file, "rt") :
  'raw = FALSE' but '~/Proyectos/EduardoAndres/Rhapsody/dataset_test/Munain_Run3_NextS/' is not a regular file
2: In file(file, "rt") :
  cannot open file '/Users/eandres/Proyectos/EduardoAndres/Rhapsody/dataset_test/Munain_Run3_NextS/': it is a directory

```

If I give a tsv file: 

```
> suppressMessages(library(Seurat))
> suppressMessages(library(scRepertoire))
> contig_list = loadContigs("~/Proyectos/EduardoAndres/Rhapsody/dataset_test/Munain_Run3_NextS/airr_rearrangement.tsv",format = "AIRR")
Error in parseAIRR(df) : could not find function "parseAIRR"
```

So I've check the loadContigs functions ... and it uses this function parseAIRR that I'm no able to find within the scRepertoire functions.

SessionInfo():

> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur ... 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] C/UTF-8/C/C/C/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] scRepertoire_1.8.0 ggplot2_3.4.1      SeuratObject_4.1.3 Seurat_4.3.0      

loaded via a namespace (and not attached):
  [1] VGAM_1.1-8                  plyr_1.8.8                 
  [3] igraph_1.4.1                lazyeval_0.2.2             
  [5] sp_1.6-0                    splines_4.2.1              
  [7] powerTCR_1.18.0             listenv_0.9.0              
  [9] scattermore_0.8             GenomeInfoDb_1.34.9        
 [11] digest_0.6.31               foreach_1.5.2              
 [13] htmltools_0.5.5             viridis_0.6.2              
 [15] ggalluvial_0.12.5           fansi_1.0.4                
 [17] magrittr_2.0.3              truncdist_1.0-2            
 [19] tensor_1.5                  cluster_2.1.4              
 [21] doParallel_1.0.17           ROCR_1.0-11                
 [23] globals_0.16.2              graphlayouts_0.8.4         
 [25] matrixStats_0.63.0          spatstat.sparse_3.0-1      
 [27] colorspace_2.1-0            ggrepel_0.9.3              
 [29] rgdal_1.6-5                 dplyr_1.1.1                
 [31] RCurl_1.98-1.12             jsonlite_1.8.4             
 [33] progressr_0.13.0            spatstat.data_3.0-1        
 [35] survival_3.5-5              zoo_1.8-11                 
 [37] iterators_1.0.14            glue_1.6.2                 
 [39] polyclip_1.10-4             gtable_0.3.3               
 [41] zlibbioc_1.44.0             XVector_0.38.0             
 [43] leiden_0.4.3                DelayedArray_0.24.0        
 [45] evd_2.3-6.1                 future.apply_1.10.0        
 [47] SingleCellExperiment_1.20.1 BiocGenerics_0.44.0        
 [49] abind_1.4-5                 SparseM_1.81               
 [51] scales_1.2.1                DBI_1.1.3                  
 [53] spatstat.random_3.1-4       miniUI_0.1.1.1             
 [55] Rcpp_1.0.10                 viridisLite_0.4.1          
 [57] xtable_1.8-4                reticulate_1.28            
 [59] stats4_4.2.1                htmlwidgets_1.6.2          
 [61] httr_1.4.5                  RColorBrewer_1.1-3         
 [63] ellipsis_0.3.2              ica_1.0-3                  
 [65] pkgconfig_2.0.3             farver_2.1.1               
 [67] uwot_0.1.14                 deldir_1.0-6               
 [69] utf8_1.2.3                  tidyselect_1.2.0           
 [71] rlang_1.1.0                 reshape2_1.4.4             
 [73] later_1.3.0                 munsell_0.5.0              
 [75] tools_4.2.1                 cli_3.6.1                  
 [77] generics_0.1.3              ggridges_0.5.4             
 [79] stringr_1.5.0               fastmap_1.1.1              
 [81] goftest_1.2-3               evmix_2.12                 
 [83] fitdistrplus_1.1-8          tidygraph_1.2.3            
 [85] purrr_1.0.1                 RANN_2.6.1                 
 [87] ggraph_2.1.0                pbapply_1.7-0              
 [89] future_1.32.0               nlme_3.1-162               
 [91] mime_0.12                   compiler_4.2.1             
 [93] plotly_4.10.1               png_0.1-8                  
 [95] spatstat.utils_3.0-2        tibble_3.2.1               
 [97] tweenr_2.0.2                stringi_1.7.12             
 [99] gsl_2.1-8                   rgeos_0.6-2                
[101] cubature_2.0.4.6            lattice_0.20-45            
[103] Matrix_1.5-3                permute_0.9-7              
[105] vegan_2.6-4                 vctrs_0.6.1                
[107] stringdist_0.9.10           pillar_1.9.0               
[109] lifecycle_1.0.3             spatstat.geom_3.1-0        
[111] lmtest_0.9-40               RcppAnnoy_0.0.20           
[113] data.table_1.14.8           cowplot_1.1.1              
[115] bitops_1.0-7                irlba_2.3.5.1              
[117] httpuv_1.6.9                patchwork_1.1.2            
[119] GenomicRanges_1.50.2        R6_2.5.1                   
[121] promises_1.2.0.1            KernSmooth_2.23-20         
[123] gridExtra_2.3               IRanges_2.32.0             
[125] parallelly_1.35.0           codetools_0.2-19           
[127] MASS_7.3-58.3               SummarizedExperiment_1.28.0
[129] withr_2.5.0                 sctransform_0.3.5          
[131] S4Vectors_0.36.2            GenomeInfoDbData_1.2.9     
[133] mgcv_1.8-42                 parallel_4.2.1             
[135] grid_4.2.1                  tidyr_1.3.0                
[137] MatrixGenerics_1.10.0       Rtsne_0.16                 
[139] spatstat.explore_3.1-0      ggforce_0.4.1              
[141] Biobase_2.58.0              shiny_1.7.4

**Comment by ncborcherding** [comment] 2023-04-14 13:27
Hey @eandresleon, 

Thanks for reaching out and providing an excellent run down of the issue - there is a version issue that exists between bioconductor and github (This will be fixed in the next bioconductor release). Currently, ```loadContigs()``` exists in the github version - and there have been a lot of improvements recently as more users have test alternative pipelines, so I would actually suggest installing the dev version with: 

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

Hope that helps and let me know if you have any issues.

Nick

**Comment by eandresleon** [comment] 2023-04-14 14:05
Dear Nick, thanks for your quick response and for your jelp.

I've tried the dev version (1.7.4), and the problem is the same:


```
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/4f/h20dfkjd3y32qb66m7r88l4r0000gp/T/RtmpyFnsbF/remotescd2b7619f1bd/ncborcherding-scRepertoire-aa53796/DESCRIPTION’ (622ms)
─  preparing ‘scRepertoire’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘scRepertoire_1.7.4.tar.gz’
   
Installing package into ‘/Users/eandres/Library/R/x86_64/4.2/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘scRepertoire’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (scRepertoire)
> 
> suppressMessages(library(scRepertoire))
> contig_list = loadContigs("~/Proyectos/EduardoAndres/Rhapsody/dataset_test/Munain_Run3_NextS/",format = "AIRR")
Error in file(file, "rt") : no se puede abrir la conexión
Además: Warning messages:
1: In file(file, "rt") :
  'raw = FALSE' but '~/Proyectos/EduardoAndres/Rhapsody/dataset_test/Munain_Run3_NextS/' is not a regular file
2: In file(file, "rt") :
  cannot open file '/Users/eandres/Proyectos/EduardoAndres/Rhapsody/dataset_test/Munain_Run3_NextS/': it is a directory
> contig_list = loadContigs("~/Proyectos/EduardoAndres/Rhapsody/dataset_test/Munain_Run3_NextS/airr_rearrangement.tsv",format = "AIRR")
Error in parseAIRR(df) : no se pudo encontrar la función "parseAIRR"
>
```

**Comment by ncborcherding** [comment] 2023-04-14 14:42
Hey @eandresleon, 

Can you try restarting your R session and then loading the scRepertoire package? If that doesn't work - let's troubleshoot from there. 

Nick

**Comment by eandresleon** [comment] 2023-04-14 15:01
Yes ! It seems to work ;)

![image](https://user-images.githubusercontent.com/26959900/232080739-6b6d364c-c3a9-48ca-8e47-22e5469563e4.png)

**Comment by RainboWu** [comment] 2023-04-17 09:30
I guess there is missing an "s" in  is.null(samples), making `sample`  become a function in R 
![图片](https://user-images.githubusercontent.com/39786687/232444455-4204f5c5-74c9-465f-9bfc-5b32f277f581.png)

**Closed** 2023-04-17 09:30 UTC

**Comment by ncborcherding** [comment] 2023-04-17 09:59
Thanks I will get that fixed!
