### ISSUE TITLE
Assign same color for different clonotype

### ISSUE THREAD

**Issue by alicekao1118** [ncborcherding/scRepertoire#195] opened 2022-10-12 18:31 UTC
Thanks for developing this useful tool! It has helped a lot for my data analysis.

I kind of have one question if that's possible to color different clonotypes with same color since we manually identify some clonotypes' TRB or TRA match others with one missing, we think they are literally identical. Therefore, I'm wondering how I can modify the funtion `highlightClonotypes` to adjust individual color.

Best,
Alice

**Comment by ncborcherding** [comment] 2022-10-12 20:16
Hey Alice, 

I think if you modify the meta data of the seurat object directly, it might be the easiest solution (below is an example of what you could try). Before that, however, I would caution you to check to enure that both the TRA and TRB chains are not public (meaning shared across clonotypes or individuals). Depending on your samples, there might be varying degrees of public chains which would lead to issues. 

```
seuratObj$SelectedClonotype <- NA
seuratObj$SelectedClonotype[seuratObj$CTaa %in% c("CAVNGGSQGNLIF_CSAEREDTDTQYF", "NA_CSAEREDTDTQYF")] <- "Clone1"
```

Hope that helps, I am going to close this issue as it is not a bug per say, but I will add a note on maybe a future functionality of highlightClonotype. 

Thanks,
Nick

**Closed by ncborcherding** 2022-10-12 20:16 UTC

**Comment by alicekao1118** [comment] 2022-10-12 21:36
Thanks Nick! It works.
