### ISSUE TITLE
quantContig makeGens fun

### ISSUE THREAD

**Issue by Liripo** [ncborcherding/scRepertoire#125] opened 2021-12-06 05:39 UTC
barcode | is_cell | contig_id | high_confidence | length | chain | v_gene | d_gene | j_gene | c_gene | full_length | productive | fwr1 | fwr1_nt | cdr1 | cdr1_nt | fwr2 | fwr2_nt | cdr2 | cdr2_nt | fwr3 | fwr3_nt | cdr3 | cdr3_nt | fwr4 | fwr4_nt | reads | umis | raw_clonotype_id | raw_consensus_id | exact_subclonotype_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
AAAGTAGGTGCAGTAG-1 | TRUE | AAAGTAGGTGCAGTAG-1_contig_1 | TRUE | 538 | TRA | TRAV12-2 |   | TRAJ54 | TRAC | TRUE | TRUE | QKEVEQNSGPLSVPEGAIASLNCTYS | CAGAAGGAGGTGGAGCAGAATTCTGGACCCCTCAGTGTTCCAGAGGGAGCCATTGCCTCTCTCAACTGCACTTACAGT | DRGSQS | GACCGAGGTTCCCAGTCC | FFWYRQYSGKSPELIMS | TTCTTCTGGTACAGACAATATTCTGGGAAAAGCCCTGAGTTGATAATGTCC | IYSNGD | ATATACTCCAATGGTGAC | KEDGRFTAQLNKASQYVSLLIRDSQPSDSATYL | AAAGAAGATGGAAGGTTTACAGCACAGCTCAATAAAGCCAGCCAGTATGTTTCTCTGCTCATCAGAGACTCCCAGCCCAGTGATTCAGCCACCTACCTC | CAVKRAQKLVF | TGTGCCGTGAAGAGGGCCCAGAAGCTGGTATTT | GQGTRLTINP | GGCCAAGGAACCAGGCTGACTATCAACCCAA | 3606 | 9 | clonotype150 | clonotype150_consensus_3 | 1
AAAGTAGGTGCAGTAG-1 | TRUE | AAAGTAGGTGCAGTAG-1_contig_2 | TRUE | 482 | TRB | TRBV20-1 |   | TRBJ1-1 | TRBC1 | TRUE | TRUE | GAVVSQHPSRVICKSGTSVKIECRSL | GGTGCTGTCGTCTCTCAACATCCGAGCAGGGTTATCTGTAAGAGTGGAACCTCTGTGAAGATCGAGTGCCGTTCCCTG | DFQATT | GACTTTCAGGCCACAACT | MFWYRQFPKQSLMLMAT | ATGTTTTGGTATCGTCAGTTCCCGAAACAGAGTCTCATGCTGATGGCAACT | SNEGSKA | TCCAATGAGGGCTCCAAGGCC | TYEQGVEKDKFLINHASLTLSTLTVTSAHPEDSSFYI | ACATACGAGCAAGGCGTCGAGAAGGACAAGTTTCTCATCAACCATGCAAGCCTGACCTTGTCCACTCTGACAGTGACCAGTGCCCATCCTGAAGACAGCAGCTTCTACATC | CSAGQGRDTEAFF | TGCAGTGCTGGTCAGGGGAGGGACACTGAAGCTTTCTTT | GQGTRLTVV | GGACAAGGCACCAGACTCACAGTTGTAG | 10944 | 14 | clonotype150 | clonotype150_consensus_2 | 1
AAAGTAGGTGCAGTAG-1 | TRUE | AAAGTAGGTGCAGTAG-1_contig_3 | TRUE | 475 | TRB | TRBV4-1 |   | TRBJ1-1 | TRBC1 | TRUE | TRUE | DTEVTQTPKHLVMGMTNKKSLKCEQH | GACACTGAAGTTACCCAGACACCAAAACACCTGGTCATGGGAATGACAAATAAGAAGTCTTTGAAATGTGAACAACAT | MGHRA | ATGGGGCACAGGGCT | MYWYKQKAKKPPELMFV | ATGTATTGGTACAAGCAGAAAGCTAAGAAGCCACCGGAGCTCATGTTTGTC | YSYEKL | TACAGCTATGAGAAACTC | SINESVPSRFSPECPNSSLLNLHLHALQPEDSALYL | TCTATAAATGAAAGTGTGCCAAGTCGCTTCTCACCTGAATGCCCCAACAGCTCTCTCTTAAACCTTCACCTACACGCCCTGCAGCCAGAAGACTCAGCCCTGTATCTC | CASSAGVNTEAFF | TGCGCCAGCAGCGCCGGGGTAAACACTGAAGCTTTCTTT | GQGTRLTVV | GGACAAGGCACCAGACTCACAGTTGTAG | 15139 | 22 | clonotype150 | clonotype150_consensus_1 | 1
AAAGTAGGTGCAGTAG-1 | TRUE | AAAGTAGGTGCAGTAG-1_contig_4 | TRUE | 497 | TRA | TRAV4 |   | TRAJ13 | TRAC | TRUE | TRUE | LAKTTQPISMDSYEGQEVNITCSHN | CTTGCTAAGACCACCCAGCCCATCTCCATGGACTCATATGAAGGACAAGAAGTGAACATAACCTGTAGCCACAAC | NIATNDY | AACATTGCTACAAATGATTAT | ITWYQQFPSQGPRFIIQ | ATCACGTGGTACCAACAGTTTCCCAGCCAAGGACCACGATTTATTATTCAA | GYKTK | GGATACAAGACAAAA | VTNEVASLFIPADRKSSTLSLPRVSLSDTAVYY | GTTACAAACGAAGTGGCCTCCCTGTTTATCCCTGCCGACAGAAAGTCCAGCACTCTGAGCCTGCCCCGGGTTTCCCTGAGCGACACTGCTGTGTACTAC | CLVGAPSGGYQKVTF | TGCCTCGTGGGCGCCCCTTCTGGGGGTTACCAGAAAGTTACCTTT | GTGTKLQVIP | GGAACTGGAACAAAGCTCCAAGTCATCCCAA | 3808 | 7 | clonotype150 | clonotype150_consensus_4 | 1

如上，10x filtered_contig_annotations.csv example,when i run code
==Note: contigs data is A barcode above ==
```R
combined <- combineTCR(contigs, samples="sc5_t", ID=id, cells="T-AB")
quantContig(combined, cloneCall="gene+nt", scale = F,exportTable = T)
```
the result is 0 row. why is not 1.
And my packages sessioninfo is
```R
ther attached packages:
[1] scRepertoire_1.3.2 ggplot2_3.3.5      dplyr_1.0.6
```

**Comment by ncborcherding** [comment] 2021-12-06 11:12
Hey Liripo, 

Thanks for reaching out - Your contig annotation file seems fine, looks like a newer version of Cell Ranger, but everything should be compatible. 

A couple of questions:

1. When you are calling ```combined <- combineTCR(contigs, samples="sc5_t", ID=id, cells="T-AB")```, what is your ID/id variable? Is that already in your global environment?
2. What does ```head(combined[[1]]``` look like?

Thanks,
Nick

**Comment by Liripo** [comment] 2021-12-06 11:25
Thank you for your reply
![image](https://user-images.githubusercontent.com/54770415/144837616-65c919df-c2ab-4ea9-b6dd-a81eb7969866.png)
the test.csv is The four rows of data in the table above.
And my R is 4.1.0

**Comment by ncborcherding** [comment] 2021-12-06 13:16
Thanks for the extra information - I see what is going on now:

You have several TCRs for the same barcode - by design, unless you indicate you would like to filter the multiple cdr3s, the result will be the exclusion of this cell - hence the pan NA values. Could you try the following and see the results

```
combined <- combineTCR(contig_list, 
                samples = "PY, 
                ID = 1, cells ="T-AB", filterMulti = TRUE)
```

Thanks,
Nick

**Comment by Liripo** [comment] 2021-12-06 13:30
Thank you for your help.I tried it and it does output 1 line, but why TCR1 and TCR2 is NA?
![image](https://user-images.githubusercontent.com/54770415/144854209-eeba821e-bd63-48f3-b818-c7490b782044.png)

**Comment by ncborcherding** [comment] 2021-12-06 14:13
There was a parsing issue - should be fixed in the dev version, you can install with:

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

**Comment by Liripo** [comment] 2021-12-06 14:23
![image](https://user-images.githubusercontent.com/54770415/144862706-dfb23fff-e0c8-4e5d-ba78-b55cea9c6196.png)
I try it.And TCR1 is ok.TCR2 is NA.

**Comment by ncborcherding** [comment] 2021-12-06 15:03
I see - found the issue and already made a commit fix to the dev version. Using your data and code - got the results correct below:

```
S1 <- read.csv("~/Downloads/test.csv")
contig_list <- list(S1)
combined <- combineTCR(contig_list, 
                samples = "PY", 
                ID = 1, cells ="T-AB", filterMulti = TRUE)
head(combined[[1]])
```

<img width="920" alt="Screen Shot 2021-12-06 at 9 02 24 AM" src="https://user-images.githubusercontent.com/22754118/144869331-4cec1f76-a68d-46d0-8ee3-4a447ce1c45d.png">
n.

**Closed by ncborcherding** 2021-12-06 15:03 UTC
